//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSExampleApp.Forms.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSExampleApp.Forms.Resx.AppResources.nl", typeof(AppResources_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto(s) toevoegen.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER TOEVOEGEN.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin mode.
        /// </summary>
        public static string AdminMode {
            get {
                return ResourceManager.GetString("AdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin opties.
        /// </summary>
        public static string AdminOptionsHeader {
            get {
                return ResourceManager.GetString("AdminOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sta alstublieft Bluetooth rechten toe om het scannen te starten..
        /// </summary>
        public static string Alert_AllowBluetooth {
            get {
                return ResourceManager.GetString("Alert_AllowBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtergrond opgeslagen. Herstart de app om deze weer te geven..
        /// </summary>
        public static string Alert_BackgroundSaved {
            get {
                return ResourceManager.GetString("Alert_BackgroundSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze app heeft bluetooth rechten nodig om metingen te kunnen doen..
        /// </summary>
        public static string Alert_BluetoothDescription {
            get {
                return ResourceManager.GetString("Alert_BluetoothDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        public static string Alert_BluetoothTitle {
            get {
                return ResourceManager.GetString("Alert_BluetoothTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera probleem, Controleer of de app toestemming tot de camera heeft..
        /// </summary>
        public static string Alert_CameraPermission {
            get {
                return ResourceManager.GetString("Alert_CameraPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectie is gefaald, probeer het nog eens..
        /// </summary>
        public static string Alert_ConnectionFailed {
            get {
                return ResourceManager.GetString("Alert_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument is onverenigbaar, selecteer een ander instrument..
        /// </summary>
        public static string Alert_DeviceIncompatible {
            get {
                return ResourceManager.GetString("Alert_DeviceIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannen van instrumenten is gefaald, scannen wordt nogmaals gestart..
        /// </summary>
        public static string Alert_DiscoverFailed {
            get {
                return ResourceManager.GetString("Alert_DiscoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verwijderen van de meting is mislukt, herstart de app en probeer het nog eens..
        /// </summary>
        public static string Alert_ErrorDeleteMeasurement {
            get {
                return ResourceManager.GetString("Alert_ErrorDeleteMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het laden van de meting is mislukt, herstart de app en probeer het nog eens..
        /// </summary>
        public static string Alert_ErrorLoadingMeasurement {
            get {
                return ResourceManager.GetString("Alert_ErrorLoadingMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verwijderen van de analiet is niet gelukt. Als het probleem zich blijft voordoen herstart dan de app..
        /// </summary>
        public static string Alert_FailedDeleteAnalyte {
            get {
                return ResourceManager.GetString("Alert_FailedDeleteAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import van de afbeelding is niet gelukt, controleer of de afbeelding de juiste indeling heeft.
        /// </summary>
        public static string Alert_FailedImageImport {
            get {
                return ResourceManager.GetString("Alert_FailedImageImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import mislukt, permissies zijn niet gezet..
        /// </summary>
        public static string Alert_FailedImport {
            get {
                return ResourceManager.GetString("Alert_FailedImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import van de analiet is niet gelukt, controleer of het json bestand de juiste indeling heeft..
        /// </summary>
        public static string Alert_FailedImportAnalyte {
            get {
                return ResourceManager.GetString("Alert_FailedImportAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import methode niet gelukt, controlleer of het method bestand correct is..
        /// </summary>
        public static string Alert_FailedImportMethod {
            get {
                return ResourceManager.GetString("Alert_FailedImportMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methode niet gevonden, herinstalleer de app alstublieft..
        /// </summary>
        public static string Alert_MethodNotFound {
            get {
                return ResourceManager.GetString("Alert_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methode succesvol opgeslagen..
        /// </summary>
        public static string Alert_MethodSaved {
            get {
                return ResourceManager.GetString("Alert_MethodSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet verbonden met een instrument, maak opnieuw een connectie..
        /// </summary>
        public static string Alert_NotConnected {
            get {
                return ResourceManager.GetString("Alert_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een geldig psmethod bestand..
        /// </summary>
        public static string Alert_SelectValidMethodFile {
            get {
                return ResourceManager.GetString("Alert_SelectValidMethodFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er ging iets mis met het starten van de meting. Herstart het instrument altublieft..
        /// </summary>
        public static string Alert_SomethingWrong {
            get {
                return ResourceManager.GetString("Alert_SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel is ingesteld, herstart de app om deze te tonen..
        /// </summary>
        public static string Alert_TitleConfigured {
            get {
                return ResourceManager.GetString("Alert_TitleConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef een geldige gebruikersnaam..
        /// </summary>
        public static string Alert_ValidUserName {
            get {
                return ResourceManager.GetString("Alert_ValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actieve gebruiker kan niet verwijderd worden..
        /// </summary>
        public static string AlertActiveUserCannotBeDeleted {
            get {
                return ResourceManager.GetString("AlertActiveUserCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u deze gebruiker met alle metingen wil verwijderen?.
        /// </summary>
        public static string AlertRemoveUserDescription {
            get {
                return ResourceManager.GetString("AlertRemoveUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruiker verwijderen.
        /// </summary>
        public static string AlertRemoveUserTitle {
            get {
                return ResourceManager.GetString("AlertRemoveUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONSTER ANALYSEREN.
        /// </summary>
        public static string AnalyzingSample {
            get {
                return ResourceManager.GetString("AnalyzingSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verander gebruiker.
        /// </summary>
        public static string ChangeUser {
            get {
                return ResourceManager.GetString("ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configureer analyte.
        /// </summary>
        public static string ConfigureAnalyte {
            get {
                return ResourceManager.GetString("ConfigureAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importeer of verwijder analyte.
        /// </summary>
        public static string ConfigureAnalyteHeader {
            get {
                return ResourceManager.GetString("ConfigureAnalyteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configureer app.
        /// </summary>
        public static string ConfigureApp {
            get {
                return ResourceManager.GetString("ConfigureApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configureer achtergrond.
        /// </summary>
        public static string ConfigureBackground {
            get {
                return ResourceManager.GetString("ConfigureBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configureer method.
        /// </summary>
        public static string ConfigureMethod {
            get {
                return ResourceManager.GetString("ConfigureMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configureer titel.
        /// </summary>
        public static string ConfigureTitle {
            get {
                return ResourceManager.GetString("ConfigureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbonden met instrument.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinden...
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vervolgen.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport maken...
        /// </summary>
        public static string CreatingReport {
            get {
                return ResourceManager.GetString("CreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinding verbreken.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meng het monster met de buffer en voeg de druppel toe.
        /// </summary>
        public static string DropSenseHeader {
            get {
                return ResourceManager.GetString("DropSenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer nieuwe titel in.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer gebruikersnaam in.
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei App.
        /// </summary>
        public static string ExampleAppTitle {
            get {
                return ResourceManager.GetString("ExampleAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gevonden:.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zet de bluetooth-scanner aan om een meting te starten.
        /// </summary>
        public static string HomePageHeader {
            get {
                return ResourceManager.GetString("HomePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importeer analyt.
        /// </summary>
        public static string ImportAnalyte {
            get {
                return ResourceManager.GetString("ImportAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats de sensor en wacht tot de indicator BLAUW wordt.
        /// </summary>
        public static string InsertSensorHeader {
            get {
                return ResourceManager.GetString("InsertSensorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekende analyten.
        /// </summary>
        public static string KnownAnalytes {
            get {
                return ResourceManager.GetString("KnownAnalytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetgeschiedenis.
        /// </summary>
        public static string MeasurementHistory {
            get {
                return ResourceManager.GetString("MeasurementHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metingen.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        public static string Nederlands {
            get {
                return ResourceManager.GetString("Nederlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notities.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een psmethod bestand.
        /// </summary>
        public static string Picker_SelectMethodFile {
            get {
                return ResourceManager.GetString("Picker_SelectMethodFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhalen.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTAAT VOOR.
        /// </summary>
        public static string ResultFor {
            get {
                return ResourceManager.GetString("ResultFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meting uitvoeren.
        /// </summary>
        public static string RunMeasurement {
            get {
                return ResourceManager.GetString("RunMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster naam.
        /// </summary>
        public static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een analyte.
        /// </summary>
        public static string SelectAnalyteHeader {
            get {
                return ResourceManager.GetString("SelectAnalyteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectDeviceHeader {
            get {
                return ResourceManager.GetString("SelectDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een gebruiker uit de lijst of creër een nieuwe.
        /// </summary>
        public static string SelectOrCreateUser {
            get {
                return ResourceManager.GetString("SelectOrCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} apparaten gevonden, selecteer 1 om verder te gaan.
        /// </summary>
        public static string SelectPageMultipleReaders {
            get {
                return ResourceManager.GetString("SelectPageMultipleReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 apparaat gevonden,  selecteer om verder te gaan.
        /// </summary>
        public static string SelectPageReaderFound {
            get {
                return ResourceManager.GetString("SelectPageReaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer gebruiker.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een gebruiker om verder te gaan.
        /// </summary>
        public static string SelectUserHeader {
            get {
                return ResourceManager.GetString("SelectUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport delen.
        /// </summary>
        public static string ShareReport {
            get {
                return ResourceManager.GetString("ShareReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafiek tonen.
        /// </summary>
        public static string ShowPlot {
            get {
                return ResourceManager.GetString("ShowPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbonden met {0}.
        /// </summary>
        public static string StatusBarConnected {
            get {
                return ResourceManager.GetString("StatusBarConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinden.
        /// </summary>
        public static string StatusBarConnecting {
            get {
                return ResourceManager.GetString("StatusBarConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinding verbroken.
        /// </summary>
        public static string StatusBarDisconnected {
            get {
                return ResourceManager.GetString("StatusBarDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} apparaten gevonden.
        /// </summary>
        public static string StatusBarMultipleReaders {
            get {
                return ResourceManager.GetString("StatusBarMultipleReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 apparaat gevonden.
        /// </summary>
        public static string StatusBarReaderFound {
            get {
                return ResourceManager.GetString("StatusBarReaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruiker.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELKOM.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
